In [14]:
import numpy as np 
import gym
import random

In [15]:
env = gym.make('Taxi-v2')

env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [17]:
action_size = env.action_space.n

print("Action size ", action_size)

space_size = env.observation_space.n

print("State size", space_size)

Action size  6
State size 500


In [38]:
qtable = np.zeros((space_size,action_size))
print(qtable)
print(qtable.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(500, 6)


In [47]:
# just checking that i got the logic right

qtable[1,] = 1
qtable[2,2] = 15
qtable[0,] = [1,2,3,4,5,6]

In [48]:
print(qtable)

[[ 1.  2.  3.  4.  5.  6.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 0.  0. 15.  0.  0.  0.]
 ...
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [49]:
np.argmax(qtable[0,:])

5

In [50]:
qtable = np.zeros((space_size,action_size))

In [44]:
# Hyper parameters

total_episodes = 50000        # Total episodes
total_test_episodes = 100     # Total test episodes
max_steps = 99                # Max steps per episode

learning_rate = 0.8           # Learning rate |arbitrary values
gamma = 0.8                   # Discounting rate |arbitrary values

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [45]:
state = env.reset()
print(state)

494


In [58]:
env.action_space.sample()

1

In [64]:
env.step(0)

(494, -1, False, {'prob': 1.0})