In [2]:
!pip install gym

    100% |████████████████████████████████| 1.5MB 10.9MB/s 
    100% |████████████████████████████████| 1.0MB 9.7MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/cb/14/71/f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
Successfully built gym


In [0]:
import numpy as np
import gym
import random

In [47]:
env = gym.make('Taxi-v2')
state = env.reset()
env.render()

total_reward = 0
done = False
while not done:
    state, reward, done, info = env.step(env.action_space.sample())
    total_reward += reward
    #env.render()

print('Total reward:', total_reward)

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

Total reward: -839


In [0]:
env.close()

In [0]:
env = gym.make('Taxi-v2')

In [0]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [71]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [73]:
from IPython.display import clear_output

alpha = 0.1
gamma = 0.6
epsilon = 0.1

# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 100001):
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False
    
    while not done:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(qtable[state]) # Exploit learned values

        next_state, reward, done, info = env.step(action) 
        
        old_value = qtable[state, action]
        next_max = np.max(qtable[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        qtable[state, action] = new_value

        if reward == -10:
            penalties += 1

        state = next_state
        epochs += 1
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

Episode: 100000
Training finished.



In [76]:
episodes = 1000
rewards = []
max_steps = 99

for episode in range(episodes):
    state = env.reset()  # Assuming you already have env created as above
    total_rewards = 0
    
    for step in range(max_steps):
        action = env.action_space.sample()  # TODO your policy here!
        state, reward, done, info = env.step(env.action_space.sample())
        total_rewards += reward
        if done:
            break
    rewards.append(total_rewards)        

print('Average score over time:', sum(rewards) / episodes)

Average score over time: -388.476


In [77]:
total_epochs, total_penalties = 0, 0
episodes = 100

for _ in range(episodes):
    state = env.reset()
    epochs, penalties, reward = 0, 0, 0
    
    done = False
    
    while not done:
        action = np.argmax(qtable[state])
        state, reward, done, info = env.step(action)

        if reward == -10:
            penalties += 1

        epochs += 1

    total_penalties += penalties
    total_epochs += epochs

print(f"Results after {episodes} episodes:")
print(f"Average timesteps per episode: {total_epochs / episodes}")
print(f"Average penalties per episode: {total_penalties / episodes}")

Results after 100 episodes:
Average timesteps per episode: 12.67
Average penalties per episode: 0.0


In [82]:
for episode in range(total_episodes):
    state = env.reset()  # Assuming you already have env created as above
    total_rewards = 0
    
    
    
for step in range(max_steps):
    action = env.action_space.sample()  # TODO your policy here!
    state, reward, done, info = env.step(env.action_space.sample())
    total_rewards += reward
    if done:
        break
    rewards.append(total_rewards) 
    

print('Average score over time:', sum(rewards) / total_episodes)



Average score over time: -4.07341


In [0]:
total_episodes = 100000       
learning_rate = 0.8          
max_steps = 90              
gamma = 0.65                            

In [0]:
# more parameters
epsilon = 1.0                 
max_epsilon = 1.0           
min_epsilon = 0.01            
decay_rate = 0.1      

In [85]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## take the biggest Q value 
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)

        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
     
        state = new_state
      
        if done == True: 
            break
        
    episode += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 7.93597
[[ 0.          0.          0.          0.          0.          0.        ]
 [-1.61442809 -0.94527405 -1.61442809 -0.94527398  0.08419388 -9.94527398]
 [ 0.08419388  1.66799058  0.08383723  1.66799058  4.10460089 -7.33200942]
 ...
 [ 0.19433019  7.85323214  1.40936357 -0.48514314 -5.35370866 -4.27966987]
 [-1.98648731 -0.94527398 -1.9808819  -1.87723749 -5.06873522 -9.72298356]
 [ 9.97036907 12.131396    9.25596492 36.14285714  2.25954058  2.43608255]]
