In [1]:
#Importing Libararies
import gym
import numpy as np

In [47]:
#Environment Setup
env = gym.make("Taxi-v2")
env.reset()
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



/Users/doba/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')


In [59]:
# Random Moments
state = env.reset()
print(state)

343


In [67]:
counter = 0
reward = 1
# Change state
env.env.s = 11
env.render()
# Take an action
#0-back::1-forward::2-right::3-left
env.step(2)
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)


In [50]:
while reward != 20:
    state, reward, done, info = env.step(env.action_space.sample())
    counter += 1
print(counter)

346


In [51]:
#Q table for observation of movement
Q = np.zeros([env.observation_space.n, env.action_space.n])
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [86]:
G = 0
gamma = 0.8

In [91]:
for episode in range(0,999):
    done = False
    G, reward, counter = 0,0,0
    state = env.reset()
    while done != True:
        action = np.argmax(Q[state])
        state2, reward, done, info = env.step(action)
        Q[state,action] = (reward + gamma * np.max(Q[state2]))
        G += reward
        counter += 1
        state = state2
    if episode % 100 == 0:
        print('Episode {} Total Reward: {} counter: {}'.format(episode,G,counter,))

Episode 0 Total Reward: 11 counter: 10
Episode 100 Total Reward: 7 counter: 14
Episode 200 Total Reward: 9 counter: 12
Episode 300 Total Reward: 6 counter: 15
Episode 400 Total Reward: 9 counter: 12
Episode 500 Total Reward: 8 counter: 13
Episode 600 Total Reward: 7 counter: 14
Episode 700 Total Reward: 7 counter: 14
Episode 800 Total Reward: 12 counter: 9
Episode 900 Total Reward: 8 counter: 13
